<a href="https://colab.research.google.com/github/mr-amit-yadav/Feature-Engineering/blob/main/Handling_Imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Handling Imbalanced Dataset
1.Up Sampling <br>
2.Down Sampling

In [ ]:
import numpy as np
import pandas as pd
# Set random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [ ]:
n_class_0,n_class_1

(900, 100)

In [ ]:
## CREATE MY DATAFRAME WITH IMBALANCED DATASET
class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

In [ ]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [ ]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [ ]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [ ]:
## Upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [ ]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True, #Sample with replacement
         n_samples=len(df_majority),
         random_state=42
         )

In [ ]:
df_minority_upsampled.shape

(900, 3)

In [ ]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [ ]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [ ]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [ ]:
## Down Sampling

In [ ]:
import numpy as np
import pandas as pd
# Set random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [ ]:
## Down sampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [ ]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=True, #Sample with replacement
         n_samples=len(df_majority),
         random_state=42
         )

In [ ]:
df_majority_downsampled.shape

(900, 3)

In [ ]:
df_downsampled=pd.concat([df_minority,df_majority_downsampled])

In [ ]:
df_downsampled.target.value_counts()

target
0    900
1    100
Name: count, dtype: int64