<a href="https://colab.research.google.com/github/mr-amit-yadav/Feature-Engineering/blob/main/Target_Guided_Ordinal_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Target Guided Ordinal Encoding

It is a technique used to encode categorical variables based on their relationship with the target variable.<br>
This encoding technique is useful when we have categorical variable with a large number of unique categories, and we want to use this variable as a feature in our medicine learning model.<br>

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category.<br>
This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [ ]:
import pandas as pd

# Create a sample dataframe with a categorical variable and a target variable
df=pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,150,300]
})

In [ ]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    150
5     Paris    300

In [ ]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [ ]:
df['city_encoded']=df['city'].map(mean_price)

In [ ]:
df[['price','city_encoded']]

   price  city_encoded
0    200         175.0
1    150         150.0
2    300         300.0
3    250         250.0
4    150         175.0
5    300         300.0

In [ ]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]